import { AuditParameter } from './models.js';

export const INITIAL_AUDIT_CHECKLIST: AuditParameter[] = [
  // --- CATEGORY 1: ZERO TOLERANCE (Score: 100, Fatal: YES) ---
  {
    id: 'ZTI-001',
    category: 'ZERO_TOLERANCE',
    category_name: 'Regulatory and Operational Integrity',
    category_weight: 100,
    parameter: 'Agency Identification: Board, GST Details',
    domain: 'GST_REGISTRATION',
    fatal: true,
    severity: 'CRITICAL',
    required_evidence: ['GST Registration Certificate', 'Agency Identification Board / Details', 'PAN / Incorporation Record'],
    keywords: ['GST', 'GSTIN', 'GST Registration', 'Goods and Services Tax', 'Form GST REG-06', 'Agency Identification'],
    logic: 'SINGLE',
    evaluation_rules: ['Check for valid GSTIN or Agency Identification details'],
    enabled: true
  },
  {
    id: 'ZTI-002',
    category: 'ZERO_TOLERANCE',
    category_name: 'Regulatory and Operational Integrity',
    category_weight: 100,
    parameter: 'Agency Access Control',
    domain: 'BIOMETRIC_ACCESS_CONTROL',
    fatal: true,
    severity: 'CRITICAL',
    required_evidence: ['Biometric access log', 'ID Card system configuration', 'Physical access control policy / photos'],
    keywords: ['biometric', 'access control', 'door access', 'badge reader', 'door controller', 'punch log', 'turnstile log'],
    logic: 'SINGLE',
    distinguish_policy: true,
    evaluation_rules: ['Distinguish policy from physical/system implementation evidence'],
    enabled: true
  },
  {
    id: 'ZTI-003',
    category: 'ZERO_TOLERANCE',
    category_name: 'Regulatory and Operational Integrity',
    category_weight: 100,
    parameter: 'Dedicated workspace/systems for Phone Lending business',
    domain: 'WORKSPACE_SEGREGATION',
    fatal: true,
    severity: 'CRITICAL',
    required_evidence: ['Dedicated workspace documentation', 'System allocation sheet', 'Segregation proof'],
    keywords: ['phone lending', 'dedicated workspace', 'system allocation', 'segregated bay', 'lending desk', 'calling floor layout'],
    logic: 'SINGLE',
    evaluation_rules: ['Verify segregated space/systems dedicated to lending operations'],
    enabled: true
  },
  {
    id: 'ZTI-004',
    category: 'ZERO_TOLERANCE',
    category_name: 'Regulatory and Operational Integrity',
    category_weight: 100,
    parameter: 'DRA Passed / Trained Certificate',
    domain: 'DRA_CERTIFICATION',
    fatal: true,
    severity: 'CRITICAL',
    required_evidence: ['DRA Certificate', 'DRA Training Completion Certificate', 'Training Record'],
    keywords: ['DRA', 'Debt Recovery Agent', 'DRA Trained', 'DRA Certificate', 'NBFET', 'IIBF', 'Recovery Agent Training'],
    logic: 'SINGLE',
    requires_validity_check: true,
    expiry_required: false,
    evaluation_rules: ['Extract agent name, training status, cert number, issue date'],
    enabled: true
  },
  {
    id: 'ZTI-005',
    category: 'ZERO_TOLERANCE',
    category_name: 'Regulatory and Operational Integrity',
    category_weight: 100,
    parameter: 'Valid Police Verification (PV) / Applied for',
    domain: 'POLICE_VERIFICATION',
    fatal: true,
    severity: 'CRITICAL',
    required_evidence: ['Police Verification Report', 'Proof of Police Verification Application'],
    keywords: ['police verification', 'character certificate', 'PV report', 'police clearance', 'verification acknowledgement', 'PCC', 'PV-ACK'],
    logic: 'OR',
    requires_validity_check: true,
    expiry_required: false,
    evaluation_rules: ['Distinguish VERIFIED, APPLIED, MISSING, EXPIRED, or UNCLEAR'],
    enabled: true
  },
  {
    id: 'ZTI-006',
    category: 'ZERO_TOLERANCE',
    category_name: 'Regulatory and Operational Integrity',
    category_weight: 100,
    parameter: 'Misconduct or another breach of COC',
    domain: 'CODE_OF_CONDUCT_DISCIPLINARY',
    fatal: true,
    severity: 'CRITICAL',
    required_evidence: ['Disciplinary Log', 'Code of Conduct Breach Report', 'Compliance Declaration'],
    keywords: ['misconduct', 'code of conduct breach', 'disciplinary action', 'compliance violation', 'incident log', 'show cause notice'],
    logic: 'SINGLE',
    requires_human_review: true,
    evaluation_rules: ['Requires HUMAN REVIEW. Absence of document alone does not guarantee compliance'],
    enabled: true
  },
  {
    id: 'ZTI-007',
    category: 'ZERO_TOLERANCE',
    category_name: 'Regulatory and Operational Integrity',
    category_weight: 100,
    parameter: 'Agent Onboarding Documents Authentication',
    domain: 'AGENT_ONBOARDING',
    fatal: true,
    severity: 'CRITICAL',
    required_evidence: ['Agent Onboarding Checklist', 'KYC Authentication Record', 'Approval Form'],
    keywords: ['onboarding checklist', 'agent onboarding', 'KYC verification', 'background check', 'approval record', 'onboarding dossier'],
    logic: 'SINGLE',
    evaluation_rules: ['Check onboarding documentation and authenticated KYC records'],
    enabled: true
  },
  {
    id: 'ZTI-008',
    category: 'ZERO_TOLERANCE',
    category_name: 'Regulatory and Operational Integrity',
    category_weight: 100,
    parameter: 'Printer/Scanner restricted / USB & Cloud storage access restricted',
    domain: 'ENDPOINT_DATA_RESTRICTION',
    allowed_domains: ['ENDPOINT_SECURITY_POLICY', 'ENDPOINT_DATA_RESTRICTION_CONFIG'],
    fatal: true,
    severity: 'CRITICAL',
    required_evidence: ['Endpoint Security Policy', 'DLP / GPO Configuration Export', 'IT Audit Screenshot'],
    keywords: ['USB restriction', 'cloud storage block', 'printer restricted', 'DLP policy', 'GPO configuration', 'removable media', 'StorageDevicePolicies', 'usb_storage', 'usb_block', 'gpo_status', 'usb storage'],
    logic: 'AND',
    sub_controls: ['POLICY_EVIDENCE', 'IMPLEMENTATION_EVIDENCE'],
    requirements: [
      {
        id: 'POLICY_EVIDENCE',
        title: 'Endpoint Security Policy',
        domain: 'ENDPOINT_SECURITY_POLICY',
        evidence_types: ['ENDPOINT_SECURITY_POLICY', 'POLICY_DOCUMENT'],
        keywords: ['endpoint security policy', 'USB restriction policy', 'removable media policy', 'cloud storage policy']
      },
      {
        id: 'IMPLEMENTATION_EVIDENCE',
        title: 'Technical Implementation Configuration (GPO/DLP)',
        domain: 'ENDPOINT_DATA_RESTRICTION_CONFIG',
        evidence_types: ['DLP_GPO_CONFIGURATION_EXPORT', 'REGISTRY_BLOCK_SCREENSHOT', 'TECHNICAL_CONFIG'],
        keywords: ['DLP configuration', 'GPO export', 'USB block registry', 'removable media disabled', 'cloud storage blocked', 'StorageDevicePolicies', 'Deny_All', 'usb_storage', 'usb_block', 'gpo_status', 'usb storage']
      }
    ],
    distinguish_policy: true,
    evaluation_rules: ['Distinguish POLICY_EXISTS from IMPLEMENTATION_EVIDENCE. Both required for PASS.'],
    enabled: true
  },
  {
    id: 'ZTI-009',
    category: 'ZERO_TOLERANCE',
    category_name: 'Regulatory and Operational Integrity',
    category_weight: 100,
    parameter: 'Blacklisting of social sites/personal email ID/messaging apps',
    domain: 'WEB_COMMUNICATION_FILTERING',
    allowed_domains: ['WEB_FILTERING_POLICY', 'WEB_COMMUNICATION_FILTERING_CONFIG'],
    fatal: true,
    severity: 'CRITICAL',
    required_evidence: ['Web Filtering Policy', 'Firewall / Proxy Configuration Export', 'Endpoint Policy'],
    keywords: ['web filtering', 'blacklisting', 'social media block', 'personal email block', 'messaging apps restricted', 'proxy block', 'firewall block rule'],
    logic: 'AND',
    sub_controls: ['POLICY_EVIDENCE', 'IMPLEMENTATION_EVIDENCE'],
    requirements: [
      {
        id: 'POLICY_EVIDENCE',
        title: 'Web Filtering / Acceptable Use Policy',
        domain: 'WEB_FILTERING_POLICY',
        evidence_types: ['WEB_FILTERING_POLICY', 'POLICY_DOCUMENT'],
        keywords: ['web filtering policy', 'acceptable use policy', 'social media policy', 'internet usage policy']
      },
      {
        id: 'IMPLEMENTATION_EVIDENCE',
        title: 'Technical Filtering / Proxy Configuration',
        domain: 'WEB_COMMUNICATION_FILTERING_CONFIG',
        evidence_types: ['FIREWALL_PROXY_CONFIGURATION_EXPORT', 'URL_FILTERING_RULE_EXPORT', 'TECHNICAL_CONFIG'],
        keywords: ['firewall block rule', 'proxy blacklisting', 'URL filtering config', 'social sites blocked', 'web proxy rule', 'category deny']
      }
    ],
    distinguish_policy: true,
    evaluation_rules: ['Distinguish policy document from technical implementation evidence. Both required for PASS.'],
    enabled: true
  },
  {
    id: 'ZTI-010',
    category: 'ZERO_TOLERANCE',
    category_name: 'Regulatory and Operational Integrity',
    category_weight: 100,
    parameter: 'Clean desk policy',
    domain: 'CLEAN_DESK',
    fatal: true,
    severity: 'HIGH',
    required_evidence: ['Clean Desk Policy', 'Inspection Records', 'Audit Photos / Compliance Declarations'],
    keywords: ['clean desk', 'clean desk policy', 'workspace inspection', 'nightly audit', 'compliance declaration'],
    logic: 'SINGLE',
    distinguish_policy: true,
    requires_human_review: true,
    evaluation_rules: ['Do not conclude physical workspace compliance from policy alone'],
    enabled: true
  },

  // --- CATEGORY 2: GOVERNANCE, COMPLIANCE & INFOSEC (Score: 60, Fatal: NO) ---
  {
    id: 'GCI-001',
    category: 'GOVERNANCE_COMPLIANCE_INFOSEC',
    category_name: 'Governance, Compliance & INFOSEC',
    category_weight: 60,
    parameter: 'Valid agency ID Card and Endorsement Card (for Field)',
    domain: 'AGENCY_ID_CARD',
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['Agency ID Card Sample/Register', 'Field Endorsement Card'],
    keywords: ['agency ID card', 'endorsement card', 'field agent ID', 'identification card', 'badge issue', 'DRA endorsement'],
    logic: 'SINGLE',
    requires_validity_check: true,
    expiry_required: false,
    evaluation_rules: ['Verify validity and availability of ID and Field Endorsement cards'],
    enabled: true
  },
  {
    id: 'GCI-002',
    category: 'GOVERNANCE_COMPLIANCE_INFOSEC',
    category_name: 'Governance, Compliance & INFOSEC',
    category_weight: 60,
    parameter: 'ID Deactivation & Agent Termination process',
    domain: 'OFFBOARDING_DEACTIVATION',
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['Termination Policy', 'Deactivation Procedure', 'Agent Deactivation Log'],
    keywords: ['termination process', 'ID deactivation', 'offboarding checklist', 'deactivation log', 'exit process', 'agent termination'],
    logic: 'SINGLE',
    distinguish_policy: true,
    evaluation_rules: ['Verify deactivation process and actual termination sample records'],
    enabled: true
  },
  {
    id: 'GCI-003',
    category: 'GOVERNANCE_COMPLIANCE_INFOSEC',
    category_name: 'Governance, Compliance & INFOSEC',
    category_weight: 60,
    parameter: 'Agency Staff in appropriate attire',
    domain: 'STAFF_ATTIRE',
    fatal: false,
    severity: 'MEDIUM',
    required_evidence: ['Dress Code Policy', 'Inspection Reports', 'Workspace Photos'],
    keywords: ['dress code', 'attire policy', 'formal wear', 'inspection report', 'attire review', 'grooming standard'],
    logic: 'SINGLE',
    requires_human_review: true,
    evaluation_rules: ['Requires HUMAN REVIEW if physical evidence is ambiguous'],
    enabled: true
  },
  {
    id: 'GCI-004',
    category: 'GOVERNANCE_COMPLIANCE_INFOSEC',
    category_name: 'Governance, Compliance & INFOSEC',
    category_weight: 60,
    parameter: 'Refresher trainings conducted; mandatory attendance sheet',
    domain: 'REFRESHER_TRAINING',
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['Refresher Training Module', 'Attendance Sheet', 'Training Records'],
    keywords: ['refresher training', 'attendance sheet', 'mandatory training', 'training log', 'participant list', 'training attendance'],
    logic: 'SINGLE',
    evaluation_rules: ['Extract training name, date, participants, attendance, trainer, completion status'],
    enabled: true
  },
  {
    id: 'GCI-005',
    category: 'GOVERNANCE_COMPLIANCE_INFOSEC',
    category_name: 'Governance, Compliance & INFOSEC',
    category_weight: 60,
    parameter: 'Agency Performance and Evaluation',
    domain: 'PERFORMANCE_NDC',
    fatal: false,
    severity: 'MEDIUM',
    required_evidence: ['Target vs Actual Report', 'Performance Memos', 'No Dues Certificate (NDC)', 'Asset Management Declaration'],
    keywords: ['target vs actual', 'performance report', 'NDC', 'no dues certificate', 'no demand certificate', 'asset management declaration', 'agency evaluation'],
    logic: 'SINGLE',
    evaluation_rules: ['Check performance evaluation records and NDC declarations'],
    enabled: true
  },
  {
    id: 'GCI-006',
    category: 'GOVERNANCE_COMPLIANCE_INFOSEC',
    category_name: 'Governance, Compliance & INFOSEC',
    category_weight: 60,
    parameter: 'Snipping Tool & MS Paint disabled',
    domain: 'SCREEN_CAPTURE_RESTRICTION',
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['Endpoint Security Configuration', 'GPO AppLocker / Software Restriction Policy', 'Device Audit Log'],
    keywords: ['snipping tool disabled', 'ms paint disabled', 'screen capture restricted', 'AppLocker policy', 'software restriction policy', 'snippingtool.exe'],
    logic: 'SINGLE',
    distinguish_policy: true,
    evaluation_rules: ['Technical audit configuration required. Policy document alone must NOT pass'],
    enabled: true
  },
  {
    id: 'GCI-007',
    category: 'GOVERNANCE_COMPLIANCE_INFOSEC',
    category_name: 'Governance, Compliance & INFOSEC',
    category_weight: 60,
    parameter: 'Password policy of agencies being followed',
    domain: 'PASSWORD_POLICY',
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['Password Policy Document', 'Active Directory Password Policy Export', 'IAM Compliance Report'],
    keywords: ['password policy', 'complexity requirements', 'password expiration', 'Active Directory GPO', 'IAM policy', 'lockout threshold'],
    logic: 'SINGLE',
    distinguish_policy: true,
    evaluation_rules: ['Verify policy document and Active Directory / GPO configuration proof'],
    enabled: true
  },
  {
    id: 'GCI-008',
    category: 'GOVERNANCE_COMPLIANCE_INFOSEC',
    category_name: 'Governance, Compliance & INFOSEC',
    category_weight: 60,
    parameter: 'Updated Windows OS',
    domain: 'OS_PATCH_MANAGEMENT',
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['Patch Compliance Report', 'Endpoint Inventory Export', 'Windows Version / Build Log'],
    keywords: ['windows update', 'patch compliance', 'OS version', 'build number', 'WSUS report', 'endpoint inventory', 'patch management'],
    logic: 'SINGLE',
    evaluation_rules: ['Analyze endpoint OS versions/builds against current patch baseline'],
    enabled: true
  },

  // --- CATEGORY 3: INFRASTRUCTURE & PROCESS MANAGEMENT (Score: 40, Fatal: NO) ---
  {
    id: 'IPM-001',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'PF & ESIC Registration Certificate OR Principal Employer Registration Certificate',
    domain: 'PF_ESIC_PRINCIPAL_EMPLOYER',
    allowed_domains: ['PF_ESIC_REGISTRATION', 'PRINCIPAL_EMPLOYER_CERTIFICATE'],
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['PF Registration Certificate', 'ESIC Registration Certificate', 'Principal Employer Registration Certificate'],
    keywords: ['PF registration', 'provident fund', 'ESIC certificate', 'principal employer', 'EPFO registration'],
    logic: 'OR',
    sub_controls: ['PF_ESIC_REGISTRATION', 'PRINCIPAL_EMPLOYER_CERTIFICATE'],
    requirements: [
      {
        id: 'PF_ESIC_REGISTRATION',
        title: 'PF & ESIC Registration Certificate',
        domain: 'PF_ESIC_REGISTRATION',
        evidence_types: ['PF_ESIC_CERTIFICATE', 'PF_REGISTRATION', 'ESIC_REGISTRATION'],
        keywords: ['PF registration', 'provident fund', 'ESIC certificate', 'EPFO registration', 'ESIC code', 'establishment code', 'PF', 'ESIC', 'EPFO']
      },
      {
        id: 'PRINCIPAL_EMPLOYER_CERTIFICATE',
        title: 'Principal Employer Registration Certificate (Form I/II)',
        domain: 'PRINCIPAL_EMPLOYER_CERTIFICATE',
        evidence_types: ['PRINCIPAL_EMPLOYER_CERTIFICATE', 'CLRA_REGISTRATION'],
        keywords: ['principal employer', 'contract labour', 'form i', 'form ii', 'clra registration', 'certificate of registration of principal employer']
      }
    ],
    evaluation_rules: ['PASS if valid evidence for PF & ESIC OR Principal Employer Certificate exists'],
    enabled: true
  },
  {
    id: 'IPM-002',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'HR & Anti-Sexual Harassment Policy',
    domain: 'HR_POSH_POLICY',
    fatal: false,
    severity: 'MEDIUM',
    required_evidence: ['HR Policy', 'POSH Policy Document', 'Employee Handbook'],
    keywords: ['HR policy', 'POSH policy', 'sexual harassment', 'employee handbook', 'ICC committee', 'internal complaints committee'],
    logic: 'SINGLE',
    evaluation_rules: ['Verify policy existence, version, effective date, and approval status'],
    enabled: true
  },
  {
    id: 'IPM-003',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'Rent or Lease Agreement for agency premises & Shops and Establishment Certificate',
    domain: 'PREMISES_AND_ESTABLISHMENT',
    allowed_domains: ['RENT_LEASE_AGREEMENT', 'SHOPS_ESTABLISHMENT_CERTIFICATE'],
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['Rent / Lease Agreement', 'Shops and Establishment Certificate'],
    keywords: ['rent agreement', 'lease agreement', 'shops and establishment', 'premises agreement', 'commercial lease'],
    logic: 'AND',
    sub_controls: ['RENT_LEASE_AGREEMENT', 'SHOPS_ESTABLISHMENT_CERTIFICATE'],
    requirements: [
      {
        id: 'RENT_LEASE_AGREEMENT',
        title: 'Rent or Lease Agreement for agency premises',
        domain: 'RENT_LEASE_AGREEMENT',
        evidence_types: ['LEASE_AGREEMENT', 'RENT_AGREEMENT'],
        keywords: ['rent agreement', 'lease agreement', 'premises agreement', 'commercial lease', 'lessor', 'lessee', 'landlord', 'tenant', 'demised premises']
      },
      {
        id: 'SHOPS_ESTABLISHMENT_CERTIFICATE',
        title: 'Shops and Establishment Act Registration Certificate',
        domain: 'SHOPS_ESTABLISHMENT_CERTIFICATE',
        evidence_types: ['SHOPS_ESTABLISHMENT_CERTIFICATE', 'SHOPS_ACT_REGISTRATION'],
        keywords: ['shops and establishment', 'shops & establishment', 'form c', 'shops act', 'commercial establishment act', 'shops registration']
      }
    ],
    evaluation_rules: ['Only PASS when BOTH Rent/Lease Agreement AND Shops & Establishment Certificate exist'],
    enabled: true
  },
  {
    id: 'IPM-004',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'Commercial General Liability Insurance (Telecalling Agency)',
    domain: 'COMMERCIAL_GENERAL_LIABILITY_INSURANCE',
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['Commercial General Liability Insurance Policy'],
    keywords: ['commercial general liability', 'CGL policy', 'insurance policy', 'liability coverage', 'indemnity insurance', 'policy schedule'],
    logic: 'SINGLE',
    requires_validity_check: true,
    expiry_required: true,
    evaluation_rules: ['Extract policy number, insured org, coverage amount, start date, expiry date, insurer. Check validity vs audit date'],
    enabled: true
  },
  {
    id: 'IPM-005',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'Visitor register maintained by the agency',
    domain: 'VISITOR_REGISTER',
    fatal: false,
    severity: 'MEDIUM',
    required_evidence: ['Visitor Register Log', 'Visitor Entry Register CSV/PDF/Scan'],
    keywords: ['visitor register', 'visitor log', 'guest register', 'visitor entry', 'access log book', 'visitor pass'],
    logic: 'SINGLE',
    evaluation_rules: ['Verify register records exist for the active audit period'],
    enabled: true
  },
  {
    id: 'IPM-006',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'CCTV installed with recordings retained for minimum 90 days',
    domain: 'CCTV_SURVEILLANCE_RETENTION',
    allowed_domains: ['CCTV_INSTALLATION', 'CCTV_RETENTION_CONFIG'],
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['CCTV System Configuration', 'Retention Log / Storage Settings Export', 'CCTV Audit Photos'],
    keywords: ['CCTV', 'surveillance camera', 'recording retention', '90 days retention', 'DVR config', 'NVR retention'],
    logic: 'AND',
    sub_controls: ['CCTV_INSTALLED', 'CCTV_RETENTION_90_DAYS'],
    requirements: [
      {
        id: 'CCTV_INSTALLED',
        title: 'CCTV Camera Installation & Inventory',
        domain: 'CCTV_INSTALLATION',
        evidence_types: ['CCTV_INSTALLATION_RECORD', 'CAMERA_INVENTORY', 'CCTV_SYSTEM_CONFIG', 'CCTV_RETENTION_CONFIGURATION'],
        keywords: ['cctv installation', 'camera inventory', 'surveillance camera', 'camera layout', 'installed cameras', 'dvr installation', 'cctv installed', 'cctv system', 'cameras']
      },
      {
        id: 'CCTV_RETENTION_90_DAYS',
        title: 'CCTV Recording Retention Configuration (Minimum 90 Days)',
        domain: 'CCTV_RETENTION_CONFIG',
        evidence_types: ['CCTV_RETENTION_CONFIGURATION', 'STORAGE_RETENTION_LOG', 'CCTV_SYSTEM_CONFIG'],
        keywords: ['90 days retention', 'recording retention', 'retention period', 'dvr config', 'nvr retention', 'storage retention', 'days retention', '90 days', 'retention settings']
      }
    ],
    distinguish_policy: true,
    evaluation_rules: ['Compound check: CCTV installed AND storage retention >= 90 days. Policy document alone cannot pass.'],
    enabled: true
  },
  {
    id: 'IPM-007',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'Fire Extinguisher available, functional, and not expired',
    domain: 'FIRE_EXTINGUISHER_SAFETY',
    fatal: false,
    severity: 'MEDIUM',
    required_evidence: ['Fire Extinguisher Inspection Certificate', 'Maintenance Log', 'Inspection Tag Photos'],
    keywords: ['fire extinguisher', 'extinguisher inspection', 'refill date', 'fire safety tag', 'pressure gauge status', 'cylinder tag'],
    logic: 'GROUP',
    sub_controls: ['AVAILABLE', 'FUNCTIONAL', 'NOT_EXPIRED'],
    requirements: [
      {
        id: 'AVAILABLE',
        title: 'Fire Extinguisher Available on Premises',
        domain: 'FIRE_EXTINGUISHER_SAFETY',
        evidence_types: ['FIRE_EXTINGUISHER_INSPECTION', 'FIRE_SAFETY_EQUIPMENT'],
        keywords: ['fire extinguisher', 'extinguisher tag', 'equipment location', 'cylinder']
      },
      {
        id: 'FUNCTIONAL',
        title: 'Fire Extinguisher Functional & Inspected',
        domain: 'FIRE_EXTINGUISHER_SAFETY',
        evidence_types: ['FIRE_EXTINGUISHER_INSPECTION', 'FIRE_SAFETY_EQUIPMENT'],
        keywords: ['pressure gauge', 'functional', 'cylinder inspection', 'serviceability', 'gauge green', 'pressure ok']
      },
      {
        id: 'NOT_EXPIRED',
        title: 'Fire Extinguisher Refill Not Expired',
        domain: 'FIRE_EXTINGUISHER_SAFETY',
        evidence_types: ['FIRE_EXTINGUISHER_INSPECTION', 'FIRE_SAFETY_EQUIPMENT'],
        keywords: ['refill date', 'due date', 'not expired', 'validity', 'next inspection'],
        requires_validity_check: true,
        expiry_required: true
      }
    ],
    requires_validity_check: true,
    expiry_required: true,
    evaluation_rules: ['Verify availability, functional status, and unexpired refill date'],
    enabled: true
  },
  {
    id: 'IPM-008',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'Fire Drill conducted by the agency (latest one year)',
    domain: 'FIRE_DRILL_RECENCY',
    fatal: false,
    severity: 'MEDIUM',
    required_evidence: ['Fire Drill Report', 'Fire Drill Attendance Record'],
    keywords: ['fire drill', 'evacuation drill', 'mock drill', 'fire drill report', 'fire safety drill'],
    logic: 'SINGLE',
    requires_validity_check: true,
    expiry_required: false,
    validity_type: 'RECENCY',
    max_age_days: 365,
    evaluation_rules: ['Extract drill date and compare against audit date. FAIL if drill date > 1 year before audit date'],
    enabled: true
  },
  {
    id: 'IPM-009',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'Power Backup / Internet Backup / Antivirus on systems',
    domain: 'INFRASTRUCTURE_REDUNDANCY_EDR',
    allowed_domains: ['POWER_BACKUP', 'INTERNET_BACKUP', 'ANTIVIRUS_EDR'],
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['UPS / Generator Maintenance Log', 'Secondary ISP Lease / Config', 'Antivirus Console Report'],
    keywords: ['power backup', 'UPS', 'generator', 'secondary ISP', 'internet backup', 'antivirus', 'endpoint protection', 'EDR'],
    logic: 'GROUP',
    sub_controls: ['POWER_BACKUP', 'INTERNET_BACKUP', 'ANTIVIRUS'],
    requirements: [
      {
        id: 'POWER_BACKUP',
        title: 'Operational Power Backup (UPS / Generator / Inverter)',
        domain: 'POWER_BACKUP',
        evidence_types: ['POWER_BACKUP_LOG', 'UPS_MAINTENANCE', 'GENERATOR_LOG'],
        keywords: ['power backup', 'UPS', 'generator', 'dg set', 'battery bank', 'load test', 'inverter backup']
      },
      {
        id: 'INTERNET_BACKUP',
        title: 'Secondary Redundant Internet Link / ISP Failover',
        domain: 'INTERNET_BACKUP',
        evidence_types: ['INTERNET_BACKUP_CONFIG', 'SECONDARY_ISP_LEASE', 'DUAL_WAN_CONFIG'],
        keywords: ['internet backup', 'secondary ISP', 'dual-WAN', 'failover link', 'redundant internet', 'secondary leased line', 'backup broadband']
      },
      {
        id: 'ANTIVIRUS',
        title: 'Antivirus / Endpoint Protection (EDR) with Up-to-date Definitions',
        domain: 'ANTIVIRUS_EDR',
        evidence_types: ['ANTIVIRUS_CONSOLE_REPORT', 'ENDPOINT_PROTECTION_EXPORT', 'EDR_STATUS'],
        keywords: ['antivirus', 'endpoint protection', 'EDR', 'crowdstrike', 'windows defender', 'virus definitions', 'definitions up to date', 'antivirus console']
      }
    ],
    evaluation_rules: ['Evaluate three sub-controls individually and return individual evidence status'],
    enabled: true
  },
  {
    id: 'IPM-010',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'Business Continuity Plan of the agency',
    domain: 'BUSINESS_CONTINUITY_PLAN',
    fatal: false,
    severity: 'MEDIUM',
    required_evidence: ['Business Continuity Plan (BCP) Document', 'Disaster Recovery Plan'],
    keywords: ['business continuity plan', 'BCP', 'disaster recovery', 'DR plan', 'continuity procedure', 'recovery time objective'],
    logic: 'SINGLE',
    evaluation_rules: ['Verify BCP policy existence, approval status, version, and review date'],
    enabled: true
  },
  {
    id: 'IPM-011',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'Escalation Matrix available with Collection agency',
    domain: 'ESCALATION_MATRIX',
    fatal: false,
    severity: 'MEDIUM',
    required_evidence: ['Escalation Matrix Document', 'Contact Hierarchy Chart'],
    keywords: ['escalation matrix', 'escalation hierarchy', 'contact matrix', 'grievance escalation', 'support contact list', 'level 1', 'level 4'],
    logic: 'SINGLE',
    evaluation_rules: ['Verify presence of structured escalation contact roles and levels'],
    enabled: true
  }
];
